export const defectsList = {
  english: [
    "Acessories defects",
    "Broken Stitching",
    "Chalk marks/pencil marks",
    "Color-Shading /  shaded parts",
    "Cracked  seam",
    "Cut damage",
    "Defective Stitching",
    "Dirty Mark - Others",
    "Drop Stich",
    "Embroidery/Applique-Others (Heat transfer / printing defects)",
    "Fullness",
    "Insecure backstitch",
    "Join Stiching - Misalign",
    "Knitted Defects - Others",
    "Needle Holes",
    "Oil Spots",
    "Others",
    "Pleated Seam",
    "Poor Neck Shape",
    "Poor color matching against standard",
    "Poor pressing / Ironing",
    "Raw Edge",
    "SPI (Stitch density: Too Loose / Tight)",
    "Seam Waviness",
    "Seam puckering",
    "Skipped stitches",
    "Sticker/label : Damaged/Incorrect",
    "Stitching- Bar tacks: missing",
    "Stitching-Seam slippage",
    "Stitching-Seam-Open",
    "Trimming & Thread: Untrimmed",
    "Twisted seam / Seam Rolling",
    "Uneven seam",
    "Workmanship-Slanted/Uncentered",
    "Zipper Defects",
  ],
  khmer: [
    "បញ្ហាផ្លាក",
    "ដាច់អំបោះ",
    "ស្នាមដីស/ខ្មៅដៃ",
    "ខុសពណ៏រលោះ",
    "រលោះអំបោះ",
    "កាត់រហែក",
    "អត់បានដេរ",
    "ប្រឡាក់",
    "ធ្លាក់ទឹក",
    "ព្រីននិងប៉ាក់",
    "ដកសាច់",
    "ដេរអត់ជាប់ថ្នេរ",
    "តូចធំ",
    "ឆ្នូតក្រណាត់",
    "ធ្លុះរន្ធ",
    "ប្រឡាក់ប្រេង",
    "អាវកែផ្សេងៗ",
    "ដេរគៀប",
    "ខូចរាងក",
    "ខុសពណ៌ពីគំរូ",
    "អ៊ុតអត់ស្អាត",
    "សល់ជាយ/ព្រុយ",
    "ថ្នេរតឹង/ធូរពេក",
    "រលក",
    "ជ្រួញ",
    "លោតអៅបោះ",
    "ដេរខុសសេរីនិងដេរខុសផ្លាក",
    "ភ្លេចបាតិះ",
    "ធ្លាក់ថ្នេរ",
    "រហែកថ្នេរ",
    "ព្រុយ",
    "ដេររមួល",
    "ដេរអត់ស្មើ",
    "មិនចំកណ្តាល",
    "បញ្ហារូត",
  ],
  chinese: [
    "物料问题",
    "斷線",
    "粉/笔印",
    "色差",
    "爆縫",
    "剪烂",
    "漏車縫/漏空",
    "髒污",
    "落坑",
    "燙畫/印花/繡花",
    "鼓起",
    "不牢固",
    "平车压线有大小",
    "布疵",
    "破洞 (包括針洞)",
    "油漬",
    "其它返工",
    "打折",
    "领型不良",
    "染色不正確 - 次品/廢品",
    "熨燙不良",
    "毛邊",
    "針距: 線緊/線鬆",
    "波浪",
    "起皺",
    "跳線",
    "錯碼/車錯嘜頭",
    "漏打枣 / 钮门",
    "缝合线滑移缺陷",
    "爆縫",
    "線頭",
    "扭/變形",
    "不對稱 / 長短不齊",
    "斜/不正中",
    "拉链问题",
  ],
  all: [
    "Acessories defects \\ បញ្ហាផ្លាក \\物料问题",
    "Broken Stitching \\ ដាច់អំបោះ  \\斷線",
    "Chalk marks/pencil marks \\ ស្នាមដីស/ខ្មៅដៃ \\粉/笔印",
    "Color-Shading /  shaded parts \\ ខុសពណ៏ \\色差",
    "Cracked  seam \\ រលោះអំបោះ \\爆縫",
    "Cut damage \\ កាត់រហែក \\剪烂",
    "Defective Stitching \\  អត់បានដេរ \\ 漏車縫/漏空",
    "Dirty Mark - Others \\ ប្រឡាក់  \\ 髒污",
    "Drop Stich \\ ធ្លាក់ទឹក \\落坑",
    "Embroidery/Applique-Others (Heat transfer / printing defects) \\ ព្រីននិងប៉ាក់ \\燙畫/印花/繡花",
    "Fullness \\ ដកសាច់ \\鼓起",
    "Insecure backstitch \\  ដេរអត់ជាប់ \\不牢固",
    "Join Stiching - Misalign \\ ថ្នេរតូចធំ \\平车压线有大小",
    "Knitted Defects - Others \\ ឆ្នូតក្រណាត់ \\布疵",
    "Needle Holes \\  ធ្លុះរន្ធ \\ 破洞 (包括針洞)",
    "Oil Spots \\ ប្រឡាក់ប្រេង \\油漬",
    "Others \\ អាវកែផ្សេងៗ \\其它返工",
    "Pleated Seam \\ ដេរគៀប \\打折",
    "Poor Neck Shape \\ ខូចរាងក \\领型不良",
    "Poor color matching against standard \\ ខុសពណ៌ពីគំរូ \\ 染色不正確 - 次品/廢品",
    "Poor pressing / Ironing \\ អ៊ុតអត់ស្អាត \\熨燙不良",
    "Raw Edge \\  សល់ជាយ/ព្រុយ \\ 毛邊",
    "SPI (Stitch density: Too Loose / Tight) \\ ថ្នេរតឹង/ធូរពេក \\ 針距: 線緊/線鬆",
    "Seam Waviness \\ រលក \\波浪",
    "Seam puckering \\  ជ្រួញ \\起皺",
    "Skipped stitches \\ លោតអៅបោះ  \\ 跳線",
    "Sticker/label : Damaged/Incorrect \\ ដេរខុសសេរីនិងដេរខុសផ្លាក \\ 錯碼/車錯嘜頭",
    "Stitching- Bar tacks: missing \\ ភ្លេចបាតិះ \\漏打枣 / 钮门",
    "Stitching-Seam slippage \\ ធ្លាក់ថ្នេរ \\缝合线滑移缺陷",
    "Stitching-Seam-Open \\ រហែកថ្នេរ \\爆縫",
    "Trimming & Thread: Untrimmed \\ ព្រុយ \\ 線頭",
    "Twisted seam / Seam Rolling \\ ដេររមួល \\扭/變形",
    "Uneven seam \\ ដេរអត់ស្មើ \\不對稱 / 長短不齊",
    "Workmanship-Slanted/Uncentered \\ មិនចំកណ្តាល \\斜/不正中",
    "Zipper Defects \\ បញ្ហារូត \\拉链问题",
  ],
};

export const factories = [
  "CJ2",
  "Combo H/Some",
  "Da Cheng",
  "De Quan",
  "Elite",
  "Elite-YM",
  "FHM",
  "HL",
  "JC",
  "Newest",
  "Sunicon",
  "VCOFF",
  "Wing Ying",
  "XYW",
  "ZX",
  "Enternal Fame",
  "KFINE",
  "SYD",
  "Hong Cheng",
  "Blue Vista",
];

export const styleCodes = [
  { code: "PTAR", customer: "Aritzia" },
  { code: "GPAR", customer: "Aritzia" },
  { code: "GPRT", customer: "Aritzia" },
  { code: "PTCOC", customer: "Costco" },
  { code: "PTCOT", customer: "Costco" },
  { code: "PTCOU", customer: "Costco" },
  { code: "PTCOR", customer: "Costco" },
  { code: "PTCOX", customer: "Costco" },
  { code: "PTCOM", customer: "Costco" },
  { code: "PTRT", customer: "Reitmans" },
  { code: "PTAF", customer: "A&F" },
];
